// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/otp/service.proto

package otp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_otp_service_proto protoreflect.FileDescriptor

const file_proto_otp_service_proto_rawDesc = "" +
	"\n" +
	"\x17proto/otp/service.proto\x12\x03otp\x1a\x18proto/otp/type/otp.proto\x1a\x1bgoogle/protobuf/empty.proto2\x80\x01\n" +
	"\n" +
	"OtpService\x125\n" +
	"\x04Send\x12\x15.otp.type.SendRequest\x1a\x16.google.protobuf.Empty\x12;\n" +
	"\x06Verify\x12\x17.otp.type.VerifyRequest\x1a\x18.otp.type.VerifyResponseB1Z/github.com/faujiahmat/cleuse-proto/protogen/otpb\x06proto3"

var file_proto_otp_service_proto_goTypes = []any{
	(*SendRequest)(nil),    // 0: otp.type.SendRequest
	(*VerifyRequest)(nil),  // 1: otp.type.VerifyRequest
	(*emptypb.Empty)(nil),  // 2: google.protobuf.Empty
	(*VerifyResponse)(nil), // 3: otp.type.VerifyResponse
}
var file_proto_otp_service_proto_depIdxs = []int32{
	0, // 0: otp.OtpService.Send:input_type -> otp.type.SendRequest
	1, // 1: otp.OtpService.Verify:input_type -> otp.type.VerifyRequest
	2, // 2: otp.OtpService.Send:output_type -> google.protobuf.Empty
	3, // 3: otp.OtpService.Verify:output_type -> otp.type.VerifyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_otp_service_proto_init() }
func file_proto_otp_service_proto_init() {
	if File_proto_otp_service_proto != nil {
		return
	}
	file_proto_otp_type_otp_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_otp_service_proto_rawDesc), len(file_proto_otp_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_otp_service_proto_goTypes,
		DependencyIndexes: file_proto_otp_service_proto_depIdxs,
	}.Build()
	File_proto_otp_service_proto = out.File
	file_proto_otp_service_proto_goTypes = nil
	file_proto_otp_service_proto_depIdxs = nil
}
