// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/product/type/product.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint32               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductIds) Reset() {
	*x = ProductIds{}
	mi := &file_proto_product_type_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductIds) ProtoMessage() {}

func (x *ProductIds) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductIds.ProtoReflect.Descriptor instead.
func (*ProductIds) Descriptor() ([]byte, []int) {
	return file_proto_product_type_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductIds) GetIds() []uint32 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ProductOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,json=order_id,proto3" json:"orderId,omitempty"`
	ProductId     uint32                 `protobuf:"varint,2,opt,name=productId,json=product_id,proto3" json:"productId,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=productName,json=product_name,proto3" json:"productName,omitempty"`
	Quantity      uint32                 `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Image         string                 `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	Price         uint32                 `protobuf:"varint,7,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductOrder) Reset() {
	*x = ProductOrder{}
	mi := &file_proto_product_type_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOrder) ProtoMessage() {}

func (x *ProductOrder) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOrder.ProtoReflect.Descriptor instead.
func (*ProductOrder) Descriptor() ([]byte, []int) {
	return file_proto_product_type_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductOrder) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ProductOrder) GetProductId() uint32 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *ProductOrder) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ProductOrder) GetQuantity() uint32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ProductOrder) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ProductOrder) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type ReduceStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductOrder        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceStocksRequest) Reset() {
	*x = ReduceStocksRequest{}
	mi := &file_proto_product_type_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceStocksRequest) ProtoMessage() {}

func (x *ReduceStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceStocksRequest.ProtoReflect.Descriptor instead.
func (*ReduceStocksRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_type_product_proto_rawDescGZIP(), []int{2}
}

func (x *ReduceStocksRequest) GetData() []*ProductOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

type RollbackStocksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ProductOrder        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackStocksRequest) Reset() {
	*x = RollbackStocksRequest{}
	mi := &file_proto_product_type_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackStocksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackStocksRequest) ProtoMessage() {}

func (x *RollbackStocksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_product_type_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackStocksRequest.ProtoReflect.Descriptor instead.
func (*RollbackStocksRequest) Descriptor() ([]byte, []int) {
	return file_proto_product_type_product_proto_rawDescGZIP(), []int{3}
}

func (x *RollbackStocksRequest) GetData() []*ProductOrder {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_product_type_product_proto protoreflect.FileDescriptor

const file_proto_product_type_product_proto_rawDesc = "" +
	"\n" +
	" proto/product/type/product.proto\x12\fproduct.type\"\x1e\n" +
	"\n" +
	"ProductIds\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\rR\x03ids\"\xb3\x01\n" +
	"\fProductOrder\x12\x19\n" +
	"\aorderId\x18\x01 \x01(\tR\border_id\x12\x1d\n" +
	"\tproductId\x18\x02 \x01(\rR\n" +
	"product_id\x12!\n" +
	"\vproductName\x18\x03 \x01(\tR\fproduct_name\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\rR\bquantity\x12\x14\n" +
	"\x05image\x18\x05 \x01(\tR\x05image\x12\x14\n" +
	"\x05price\x18\a \x01(\rR\x05price\"E\n" +
	"\x13ReduceStocksRequest\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.product.type.ProductOrderR\x04data\"G\n" +
	"\x15RollbackStocksRequest\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.product.type.ProductOrderR\x04dataB5Z3github.com/faujiahmat/cleuse-proto/protogen/productb\x06proto3"

var (
	file_proto_product_type_product_proto_rawDescOnce sync.Once
	file_proto_product_type_product_proto_rawDescData []byte
)

func file_proto_product_type_product_proto_rawDescGZIP() []byte {
	file_proto_product_type_product_proto_rawDescOnce.Do(func() {
		file_proto_product_type_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_product_type_product_proto_rawDesc), len(file_proto_product_type_product_proto_rawDesc)))
	})
	return file_proto_product_type_product_proto_rawDescData
}

var file_proto_product_type_product_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_product_type_product_proto_goTypes = []any{
	(*ProductIds)(nil),            // 0: product.type.ProductIds
	(*ProductOrder)(nil),          // 1: product.type.ProductOrder
	(*ReduceStocksRequest)(nil),   // 2: product.type.ReduceStocksRequest
	(*RollbackStocksRequest)(nil), // 3: product.type.RollbackStocksRequest
}
var file_proto_product_type_product_proto_depIdxs = []int32{
	1, // 0: product.type.ReduceStocksRequest.data:type_name -> product.type.ProductOrder
	1, // 1: product.type.RollbackStocksRequest.data:type_name -> product.type.ProductOrder
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_product_type_product_proto_init() }
func file_proto_product_type_product_proto_init() {
	if File_proto_product_type_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_type_product_proto_rawDesc), len(file_proto_product_type_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_product_type_product_proto_goTypes,
		DependencyIndexes: file_proto_product_type_product_proto_depIdxs,
		MessageInfos:      file_proto_product_type_product_proto_msgTypes,
	}.Build()
	File_proto_product_type_product_proto = out.File
	file_proto_product_type_product_proto_goTypes = nil
	file_proto_product_type_product_proto_depIdxs = nil
}
