// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/product/service.proto

package product

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_product_service_proto protoreflect.FileDescriptor

const file_proto_product_service_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/product/service.proto\x12\aproduct\x1a\x1dproto/product/type/cart.proto\x1a proto/product/type/product.proto\x1a\x1bgoogle/protobuf/empty.proto2\x85\x02\n" +
	"\x0eProductService\x12U\n" +
	"\x14FindManyByIdsForCart\x12\x18.product.type.ProductIds\x1a!.product.type.ProductCartResponse\"\x00\x12K\n" +
	"\fReduceStocks\x12!.product.type.ReduceStocksRequest\x1a\x16.google.protobuf.Empty\"\x00\x12O\n" +
	"\x0eRollbackStocks\x12#.product.type.RollbackStocksRequest\x1a\x16.google.protobuf.Empty\"\x00B5Z3github.com/faujiahmat/cleuse-proto/protogen/productb\x06proto3"

var file_proto_product_service_proto_goTypes = []any{
	(*ProductIds)(nil),            // 0: product.type.ProductIds
	(*ReduceStocksRequest)(nil),   // 1: product.type.ReduceStocksRequest
	(*RollbackStocksRequest)(nil), // 2: product.type.RollbackStocksRequest
	(*ProductCartResponse)(nil),   // 3: product.type.ProductCartResponse
	(*emptypb.Empty)(nil),         // 4: google.protobuf.Empty
}
var file_proto_product_service_proto_depIdxs = []int32{
	0, // 0: product.ProductService.FindManyByIdsForCart:input_type -> product.type.ProductIds
	1, // 1: product.ProductService.ReduceStocks:input_type -> product.type.ReduceStocksRequest
	2, // 2: product.ProductService.RollbackStocks:input_type -> product.type.RollbackStocksRequest
	3, // 3: product.ProductService.FindManyByIdsForCart:output_type -> product.type.ProductCartResponse
	4, // 4: product.ProductService.ReduceStocks:output_type -> google.protobuf.Empty
	4, // 5: product.ProductService.RollbackStocks:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_product_service_proto_init() }
func file_proto_product_service_proto_init() {
	if File_proto_product_service_proto != nil {
		return
	}
	file_proto_product_type_cart_proto_init()
	file_proto_product_type_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_product_service_proto_rawDesc), len(file_proto_product_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_product_service_proto_goTypes,
		DependencyIndexes: file_proto_product_service_proto_depIdxs,
	}.Build()
	File_proto_product_service_proto = out.File
	file_proto_product_service_proto_goTypes = nil
	file_proto_product_service_proto_depIdxs = nil
}
